name: IFI
options:
  bundleIdPrefix: com.sanozie
  deploymentTarget:
    iOS: 18.0
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: 5.0
    DEVELOPMENT_TEAM: "" # Add your team ID here

targets:
  IFI:
    type: application
    platform: iOS
    deploymentTarget: 18.0
    sources:
      - path: Sources
        name: Sources
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: IFI
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
        NSMicrophoneUsageDescription: IFI needs access to your microphone for speech-to-text functionality.
        NSSpeechRecognitionUsageDescription: IFI needs access to speech recognition for voice commands.
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sanozie.IFI
        PRODUCT_NAME: IFI
        TARGETED_DEVICE_FAMILY: 1,2 # iPhone and iPad
        SWIFT_VERSION: 5.0
        DEVELOPMENT_TEAM: "" # Add your team ID here
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    attributes:
      SystemCapabilities:
        com.apple.Speech:
          enabled: 1
        com.apple.Microphone:
          enabled: 1

schemes:
  IFI:
    build:
      targets:
        IFI: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
